### PR TITLE
fix(build): Simplified build process

### LINKED ISSUE #5: Improve build process
As discussed during review of #3, we want to clarify the build process

TODO:
- separate into smaller functions with a single responsibility
- always build manifest file even if only a single scenario has been built

Ideas:

```ts
if (require.main === module) {
    const id = process.argv.length >= 3 ? process.argv[2] : "*"
    const basePath = process.argv.length >= 4 ? process.argv[3] : "dist"

    // Get all local scenario ids

    // if build all
        // build all
    // else
        // build specific

    if (id === "*") {
        buildAll(basePath)
    } else {
        buildOne(id, basePath)
    }

    // Always update manifest with metadata from all scenarios
}
```

### PR DESCRIPTION
**Pull request by Greenheart**
Fix #5 

This will output the same scenarios as before. The two only differences are a cleaner implementation, and that the scenario manifest now will build even when you only build specific scenarios.

### CODE REVIEW

File: scripts/build-scenario.ts [hunk 1]
```diff
@@ -64,45 +65,45 @@ interface ScenarioManifest {
...
+    const outputDir = process.argv.length >= 4 ? process.argv[3] : "dist"
+    const allScenarioIds = getScenarioIds(join(__dirname, "scenarios"))
+    const ids = id === "*" ? allScenarioIds : [id]
 
-    if (id === "*") {
-        buildAll(basePath)
-    } else {
-        buildOne(id, basePath)
-    }
+    buildScenarios(ids, outputDir)
```
Comment (Greenheart) [inline scripts/build-scenario.ts:107]: Failing builds complain about I handled promise rejections here. This should be wrapped in a Promise.all() and then with a catch logging errors

**Comment by Muthaias** [comment]
Looks good. And works on my machine
